[package]
name = "rust-ztm"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cmake = "0.1.50"

[dependencies]
libc = "0.2.155"
reqwest = "0.12.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.38.0", features = ["macros"] }

[features]
agent-ui = []
